---
networks:
  opencv-code-server:
    driver: bridge
services:
  opencv-code-server:
    container_name: opencv-code-server
    environment:
      - "PUID=${CODE_SERVER_PUID}"
      - "PGID=${CODE_SERVER_PGID}"
      - TZ=Europe/Istanbul
      - "PASSWORD=${CODE_SERVER_PASSWORD}"
      - "SUDO_PASSWORD=${CODE_SERVER_SUDO_PASSWORD}"
    image: "linuxserver/code-server:v3.6.0-ls51"
    networks:
      - opencv-code-server
    restart: unless-stopped
    volumes:
      - "${CODE_SERVER_CONFIG_VOLUME}:/config"
      - "${CODE_SERVER_PROJECTS_VOLUME}:/projects"
      - "./settings/extensions.csv:/config/extensions.csv"
      - "./settings/settings.json:/config/settings.json"
  opencv-code-server-proxy:
    container_name: opencv-code-server-proxy
    depends_on:
      - opencv-code-server
    image: nginx
    networks:
      - opencv-code-server
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - "${PROXY_CERTIFICATE_PATH}:/etc/nginx/code-server.pem"
      - "${PROXY_CERTIFICATE_KEY_PATH}:/etc/nginx/code-server-key.pem"
      - "./proxy/conf.d:/etc/nginx/conf.d"
version: "3.3"
