---
networks:
  opencv-code-server:
    driver: bridge
services:
  opencv-code-server:
    container_name: opencv-code-server
    environment:
      - "DISPLAY=opencv-novnc:0.0"
      - "PUID=${CODE_SERVER_PUID}"
      - "PGID=${CODE_SERVER_PGID}"
      - TZ=Europe/Istanbul
      - "PASSWORD=${CODE_SERVER_PASSWORD}"
      - "SUDO_PASSWORD=${CODE_SERVER_SUDO_PASSWORD}"
    image: ghcr.io/works-on-my-machine/opencv-code-server:latest
    networks:
      - opencv-code-server
    restart: unless-stopped
    volumes:
      - "${CODE_SERVER_CONFIG_VOLUME}:/config"
      - "${CODE_SERVER_PROJECTS_VOLUME}:/projects"
      - "./opencv-code-server/settings/extensions.csv:/config/extensions.csv"
      - "./opencv-code-server/settings/settings.json:/config/settings.json"
      - "./opencv-code-server/example-project:/projects/example-project"
      - "./opencv-code-server/custom-cont-init.d:/config/custom-cont-init.d"
  opencv-nginx-proxy:
    container_name: opencv-nginx-proxy
    depends_on:
      - opencv-code-server
      - opencv-novnc
    image: nginx
    networks:
      - opencv-code-server
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - "${CERTIFICATE_PATH}:/etc/nginx/code-server.pem"
      - "${CERTIFICATE_KEY_PATH}:/etc/nginx/code-server-key.pem"
      - "./opencv-nginx-proxy/conf.d:/etc/nginx/conf.d"
  opencv-novnc:
    container_name: opencv-novnc
    environment:
      - "DISPLAY_WIDTH=${NOVNC_WIDTH}"
      - "DISPLAY_HEIGHT=${NOVNC_HEIGHT}"
      - RUN_XTERM=no
      - RUN_FLUXBOX=yes
    image: "theasp/novnc:latest"
    networks:
      - opencv-code-server
    restart: unless-stopped
version: "3.3"
